package net.darkhax.darkutilities.datagen;

import net.darkhax.darkutilities.DarkUtils;
import net.darkhax.darkutilities.utils.DarkUtilsTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.fabricmc.fabric.api.tag.convention.v2.ConventionalItemTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.recipes.*;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.Recipe;
import org.jspecify.annotations.NullMarked;

import java.util.concurrent.CompletableFuture;

import static net.darkhax.darkutilities.Constants.id;

@NullMarked
public class DarkRecipeProvider extends FabricRecipeProvider {
    private static class Impl extends RecipeProvider {
        protected Impl(HolderLookup.Provider provider, RecipeOutput recipeOutput) {
            super(provider, recipeOutput);
        }

        @Override
        public void buildRecipes() {
            SingleItemRecipeBuilder.stonecutting(
                            Ingredient.of(
                                    registries
                                            .lookupOrThrow(Registries.ITEM)
                                            .getOrThrow(DarkUtilsTags.Items.DARK_STONES)
                            ),
                            RecipeCategory.MISC,
                            DarkUtils.getInstance().content.blankPlate,
                            16
                    )
                    .unlockedBy("has_dark_stone", this.has(DarkUtilsTags.Items.DARK_STONES))
                    .save(this.output, "blank_plate_from_dark_stone_stonecutting");
            String genericPlateGroup = "darkutils:plate";
            var itemRegistry = registries.lookupOrThrow(Registries.ITEM);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.glowingPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.GLOWSTONE)
                    .define('B', Items.GLOW_INK_SAC)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.GLOWSTONE), has(Items.GLOWSTONE))
                    .unlockedBy(getHasName(Items.GLOW_INK_SAC), has(Items.GLOW_INK_SAC))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.anchorPlate, 3)
                    .pattern("FFF")
                    .pattern("SSS")
                    .define('F', ConventionalItemTags.SLIME_BALLS)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.SLIME_BALL), has(ConventionalItemTags.SLIME_BALLS))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.banePlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.SPIDER_EYE)
                    .define('B', Items.IRON_SWORD)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.SPIDER_EYE), has(Items.SPIDER_EYE))
                    .unlockedBy(getHasName(Items.IRON_SWORD), has(Items.IRON_SWORD))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.damagePlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.CRIMSON_FUNGUS)
                    .define('B', Items.GOLDEN_SWORD)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.CRIMSON_FUNGUS), has(Items.CRIMSON_FUNGUS))
                    .unlockedBy(getHasName(Items.GOLDEN_SWORD), has(Items.GOLDEN_SWORD))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.maimPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.SHROOMLIGHT)
                    .define('B', Items.IRON_SWORD)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.SHROOMLIGHT), has(Items.SHROOMLIGHT))
                    .unlockedBy(getHasName(Items.IRON_SWORD), has(Items.IRON_SWORD))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.playerDamagePlate, 3)
                    .pattern(" S ")
                    .pattern("CMC")
                    .pattern("PPP")
                    .define('S', Items.DIAMOND_SWORD)
                    .define('C', Items.WARPED_FUNGUS)
                    .define('M', Items.PHANTOM_MEMBRANE)
                    .define('P', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.DIAMOND_SWORD), has(Items.DIAMOND_SWORD))
                    .unlockedBy(getHasName(Items.WARPED_FUNGUS), has(Items.WARPED_FUNGUS))
                    .unlockedBy(getHasName(Items.PHANTOM_MEMBRANE), has(Items.PHANTOM_MEMBRANE))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output, recipeKey("damage_plate_player_from_phantom_membrane"));
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.playerDamagePlate, 3)
                    .pattern(" S ")
                    .pattern("CMC")
                    .pattern("PPP")
                    .define('S', Items.DIAMOND_SWORD)
                    .define('C', Items.WARPED_FUNGUS)
                    .define('M', Items.PLAYER_HEAD)
                    .define('P', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.DIAMOND_SWORD), has(Items.DIAMOND_SWORD))
                    .unlockedBy(getHasName(Items.WARPED_FUNGUS), has(Items.WARPED_FUNGUS))
                    .unlockedBy(getHasName(Items.PHANTOM_MEMBRANE), has(Items.PHANTOM_MEMBRANE))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .showNotification(true)
                    .save(output, recipeKey("damage_plate_player_from_player_head"));
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.darknessPlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('F', Items.PHANTOM_MEMBRANE)
                    .define('B', Items.INK_SAC)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.PHANTOM_MEMBRANE), has(Items.PHANTOM_MEMBRANE))
                    .unlockedBy(getHasName(Items.INK_SAC), has(Items.INK_SAC))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.fatiguePlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('F', Items.PRISMARINE_CRYSTALS)
                    .define('B', Items.PRISMARINE_SHARD)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.PRISMARINE_CRYSTALS), has(Items.PRISMARINE_CRYSTALS))
                    .unlockedBy(getHasName(Items.PRISMARINE_SHARD), has(Items.PRISMARINE_SHARD))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.flamePlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('F', Items.FLINT_AND_STEEL)
                    .define('B', Items.BLAZE_POWDER)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.FLINT_AND_STEEL), has(Items.FLINT_AND_STEEL))
                    .unlockedBy(getHasName(Items.BLAZE_POWDER), has(Items.BLAZE_POWDER))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.frostPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.SNOWBALL)
                    .define('B', Items.POWDER_SNOW_BUCKET)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.SNOWBALL), has(Items.SNOWBALL))
                    .unlockedBy(getHasName(Items.POWDER_SNOW_BUCKET), has(Items.POWDER_SNOW_BUCKET))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.hungerPlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('F', Items.NETHER_WART)
                    .define('B', Items.ROTTEN_FLESH)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.NETHER_WART), has(Items.NETHER_WART))
                    .unlockedBy(getHasName(Items.ROTTEN_FLESH), has(Items.ROTTEN_FLESH))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.levitationPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.FEATHER)
                    .define('B', Items.POPPED_CHORUS_FRUIT)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.FEATHER), has(Items.FEATHER))
                    .unlockedBy(getHasName(Items.POPPED_CHORUS_FRUIT), has(Items.POPPED_CHORUS_FRUIT))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.misfortunePlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.PHANTOM_MEMBRANE)
                    .define('B', Items.GOLD_INGOT)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.PHANTOM_MEMBRANE), has(Items.PHANTOM_MEMBRANE))
                    .unlockedBy(getHasName(Items.GOLD_INGOT), has(Items.GOLD_INGOT))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.omenPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.NETHER_WART)
                    .define('B', Items.TOTEM_OF_UNDYING)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.NETHER_WART), has(Items.NETHER_WART))
                    .unlockedBy(getHasName(Items.TOTEM_OF_UNDYING), has(Items.TOTEM_OF_UNDYING))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.poisonPlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('B', Items.POISONOUS_POTATO)
                    .define('F', Items.SPIDER_EYE)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.POISONOUS_POTATO), has(Items.POISONOUS_POTATO))
                    .unlockedBy(getHasName(Items.SPIDER_EYE), has(Items.SPIDER_EYE))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC,
                            DarkUtils.getInstance().content.slowfallPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.FEATHER)
                    .define('B', Items.PHANTOM_MEMBRANE)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.FEATHER), has(Items.FEATHER))
                    .unlockedBy(getHasName(Items.PHANTOM_MEMBRANE), has(Items.PHANTOM_MEMBRANE))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.slownessPlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('F', Items.SNOW_BLOCK)
                    .define('B', Items.SOUL_SAND)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.SNOW_BLOCK), has(Items.SNOW_BLOCK))
                    .unlockedBy(getHasName(Items.SOUL_SAND), has(Items.SOUL_SAND))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.smitePlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.GHAST_TEAR)
                    .define('B', Items.IRON_SWORD)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.GHAST_TEAR), has(Items.GHAST_TEAR))
                    .unlockedBy(getHasName(Items.IRON_SWORD), has(Items.IRON_SWORD))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.weaknessPlate, 3)
                    .pattern("BFB")
                    .pattern("SSS")
                    .define('F', Items.FERMENTED_SPIDER_EYE)
                    .define('B', Items.BROWN_MUSHROOM)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.FERMENTED_SPIDER_EYE), has(Items.FERMENTED_SPIDER_EYE))
                    .unlockedBy(getHasName(Items.BROWN_MUSHROOM), has(Items.BROWN_MUSHROOM))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.witherPlate, 3)
                    .pattern("FBF")
                    .pattern("SSS")
                    .define('F', Items.FLINT)
                    .define('B', Items.WITHER_ROSE)
                    .define('S', DarkUtilsTags.Items.PLATE_BASE)
                    .group(genericPlateGroup)
                    .unlockedBy(getHasName(Items.FLINT), has(Items.FLINT))
                    .unlockedBy(getHasName(Items.WITHER_ROSE), has(Items.WITHER_ROSE))
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .save(output);
            var vectorPlateGroup = "darkutils:vector_plate";
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.vectorPlate, 6)
                    .pattern("BBB")
                    .pattern("SDS")
                    .pattern("BBB")
                    .define('B', DarkUtilsTags.Items.PLATE_BASE)
                    .define('S', Items.SUGAR)
                    .define('D', ConventionalItemTags.SLIME_BALLS)
                    .group(vectorPlateGroup)
                    .unlockedBy("has_plate_base", has(DarkUtilsTags.Items.PLATE_BASE))
                    .unlockedBy(getHasName(Items.SUGAR), has(Items.SUGAR))
                    .unlockedBy(getHasName(Items.SLIME_BALL), has(ConventionalItemTags.SLIME_BALLS))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.vectorPlateFast, 6)
                    .pattern("BBB")
                    .pattern("SDS")
                    .pattern("BBB")
                    .define('B', DarkUtils.getInstance().content.vectorPlate)
                    .define('S', Items.GOLD_INGOT)
                    .define('D', Items.SUGAR)
                    .group(vectorPlateGroup)
                    .unlockedBy(getHasName(DarkUtils.getInstance().content.vectorPlate), has(DarkUtils.getInstance().content.vectorPlate))
                    .unlockedBy(getHasName(Items.SUGAR), has(Items.SUGAR))
                    .unlockedBy(getHasName(Items.GOLD_INGOT), has(Items.GOLD_INGOT))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.vectorPlateExtreme, 6)
                    .pattern("BBB")
                    .pattern("SDS")
                    .pattern("BBB")
                    .define('B', DarkUtils.getInstance().content.vectorPlateFast)
                    .define('S', Items.REDSTONE)
                    .define('D', Items.SUGAR)
                    .group(vectorPlateGroup)
                    .unlockedBy(getHasName(DarkUtils.getInstance().content.vectorPlateFast), has(DarkUtils.getInstance().content.vectorPlateFast))
                    .unlockedBy(getHasName(Items.SUGAR), has(Items.SUGAR))
                    .unlockedBy(getHasName(Items.REDSTONE), has(Items.REDSTONE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.redstoneRandomizer, 1)
                    .pattern("CCC")
                    .pattern("QER")
                    .pattern("CCC")
                    .define('C', DarkUtilsTags.Items.DARK_STONES)
                    .define('Q', Items.QUARTZ)
                    .define('E', Items.ENDER_PEARL)
                    .define('R', Items.REDSTONE)
                    .unlockedBy(getHasName(Items.QUARTZ), has(Items.QUARTZ))
                    .unlockedBy(getHasName(Items.ENDER_PEARL), has(Items.ENDER_PEARL))
                    .unlockedBy(getHasName(Items.REDSTONE), has(Items.REDSTONE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.shieldedRedstone, 1)
                    .pattern("CCC")
                    .pattern("CGR")
                    .pattern("CCC")
                    .define('C', DarkUtilsTags.Items.DARK_STONES)
                    .define('G', Items.GLASS)
                    .define('R', Items.REDSTONE_BLOCK)
                    .unlockedBy(getHasName(Items.GLASS), has(Items.GLASS))
                    .unlockedBy(getHasName(Items.REDSTONE_BLOCK), has(Items.REDSTONE_BLOCK))
                    .unlockedBy("has_dark_stone", has(DarkUtilsTags.Items.DARK_STONES))
                    .save(output);
            //Human Review ended here; TODO Fix unlock conditions beyond this point as gpt got lazy
            var portalCharmGroup = "darkutils:portal_charm";
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.portalCharm, 1)
                    .pattern("SSS")
                    .pattern("OCO")
                    .pattern(" O ")
                    .define('S', ConventionalItemTags.STRINGS)
                    .define('O', Items.CRYING_OBSIDIAN)
                    .define('C', Items.END_CRYSTAL)
                    .group(portalCharmGroup)
                    .unlockedBy(getHasName(Items.END_CRYSTAL), has(Items.END_CRYSTAL))
                    .unlockedBy(getHasName(Items.CRYING_OBSIDIAN), has(Items.CRYING_OBSIDIAN))
                    .save(output, recipeKey("charm_portal_end_crystal"));
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.portalCharm, 1)
                    .pattern("SSS")
                    .pattern("OCO")
                    .pattern(" O ")
                    .define('S', ConventionalItemTags.STRINGS)
                    .define('O', Items.CRYING_OBSIDIAN)
                    .define('C', Items.ENDER_EYE)
                    .group(portalCharmGroup)
                    .unlockedBy(getHasName(Items.ENDER_EYE), has(Items.ENDER_EYE))
                    .unlockedBy(getHasName(Items.CRYING_OBSIDIAN), has(Items.CRYING_OBSIDIAN))
                    .save(output, recipeKey("charm_portal_ender_eye"));
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.sleepCharm, 1)
                    .pattern("SWS")
                    .pattern("BEY")
                    .pattern("SRS")
                    .define('S', Items.GOLD_INGOT)
                    .define('W', Items.WHITE_WOOL)
                    .define('B', Items.BLACK_WOOL)
                    .define('Y', Items.YELLOW_WOOL)
                    .define('R', Items.RED_WOOL)
                    .define('E', ItemTags.BEDS)
                    .unlockedBy("has_bed", has(ItemTags.BEDS))
                    .unlockedBy(getHasName(Items.GOLD_INGOT), has(Items.GOLD_INGOT))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.wardingCharm, 1)
                    .pattern("SSS")
                    .pattern("GNG")
                    .pattern(" T ")
                    .define('S', ConventionalItemTags.STRINGS)
                    .define('G', Items.GOLD_INGOT)
                    .define('N', Items.NETHER_STAR)
                    .define('T', Items.TOTEM_OF_UNDYING)
                    .unlockedBy(getHasName(Items.NETHER_STAR), has(Items.NETHER_STAR))
                    .unlockedBy(getHasName(Items.GOLD_INGOT), has(Items.GOLD_INGOT))
                    .unlockedBy(getHasName(Items.TOTEM_OF_UNDYING), has(Items.TOTEM_OF_UNDYING))
                    .save(output);
            var group = "darkutils:filters";
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterAnimal, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.HAY_BLOCK)
                    .group(group)
                    .unlockedBy(getHasName(Items.HAY_BLOCK), has(Items.HAY_BLOCK))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterArthropod, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.SPIDER_EYE)
                    .group(group)
                    .unlockedBy(getHasName(Items.SPIDER_EYE), has(Items.SPIDER_EYE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterBaby, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.EGG)
                    .group(group)
                    .unlockedBy(getHasName(Items.EGG), has(Items.EGG))
                    .save(output);

            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterEquipment, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.GOLDEN_CHESTPLATE)
                    .group(group)
                    .unlockedBy(getHasName(Items.GOLDEN_CHESTPLATE), has(Items.GOLDEN_CHESTPLATE))
                    .save(output);

            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterFireImmune, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.BLAZE_POWDER)
                    .group(group)
                    .unlockedBy(getHasName(Items.BLAZE_POWDER), has(Items.BLAZE_POWDER))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterFreezeImmune, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.POWDER_SNOW_BUCKET)
                    .group(group)
                    .unlockedBy(getHasName(Items.POWDER_SNOW_BUCKET), has(Items.POWDER_SNOW_BUCKET))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterGolem, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.CARVED_PUMPKIN)
                    .group(group)
                    .unlockedBy(getHasName(Items.CARVED_PUMPKIN), has(Items.CARVED_PUMPKIN))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterHostile, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.ROTTEN_FLESH)
                    .group(group)
                    .unlockedBy(getHasName(Items.ROTTEN_FLESH), has(Items.ROTTEN_FLESH))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterIllager, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.CROSSBOW)
                    .group(group)
                    .unlockedBy(getHasName(Items.CROSSBOW), has(Items.CROSSBOW))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterNamed, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.NAME_TAG)
                    .group(group)
                    .unlockedBy(getHasName(Items.NAME_TAG), has(Items.NAME_TAG))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterPassenger, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.MINECART)
                    .group(group)
                    .unlockedBy(getHasName(Items.MINECART), has(Items.MINECART))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterPet, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.MILK_BUCKET)
                    .group(group)
                    .unlockedBy(getHasName(Items.MILK_BUCKET), has(Items.MILK_BUCKET))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterPlayer, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.GOLDEN_PICKAXE)
                    .group(group)
                    .unlockedBy(getHasName(Items.GOLDEN_PICKAXE), has(Items.GOLDEN_PICKAXE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterRaider, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.BELL)
                    .group(group)
                    .unlockedBy(getHasName(Items.BELL), has(Items.BELL))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterSlime, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', ConventionalItemTags.SLIME_BALLS)
                    .group(group)
                    .unlockedBy("has_slime_balls", has(ConventionalItemTags.SLIME_BALLS))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterUndead, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.BONE)
                    .group(group)
                    .unlockedBy(getHasName(Items.BONE), has(Items.BONE))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterVillager, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.EMERALD)
                    .group(group)
                    .unlockedBy(getHasName(Items.EMERALD), has(Items.EMERALD))
                    .save(output);
            ShapedRecipeBuilder.shaped(itemRegistry, RecipeCategory.MISC, DarkUtils.getInstance().content.filterWater, 4)
                    .pattern("SFS")
                    .pattern("FIF")
                    .pattern("SFS")
                    .define('F', ItemTags.FENCE_GATES)
                    .define('S', ConventionalItemTags.STONES)
                    .define('I', Items.WATER_BUCKET)
                    .group(group)
                    .unlockedBy(getHasName(Items.WATER_BUCKET), has(Items.WATER_BUCKET))
                    .save(output);


        }
    }

    public static ResourceKey<Recipe<?>> recipeKey(String path) {
        return ResourceKey.create(Registries.RECIPE, id(path));
    }

    public DarkRecipeProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected RecipeProvider createRecipeProvider(HolderLookup.Provider registryLookup, RecipeOutput exporter) {
        return new Impl(registryLookup, exporter);
    }

    @Override
    public String getName() {
        return "Recipe Provider";
    }
}
